import "./globals.css";
import Providers from "./providers";
import ThemeSwitcher from "./theme-switcher";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const panAnimatedSvg = (
  <svg
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 500 500"
    width={25}
    // height={40}
    id="cookIcon"
  >
    <g>
      <g>
        <path d="m495.4,206.3c-7.7-8.2-20.7-8.6-28.9-0.8l-131.4,124h-303.7c-11.3,0-20.4,9.1-20.4,20.4 0,83.3 67.8,151.1 151.2,151.1h50.6c80.4,0 146.3-63.1 150.9-142.4l130.9-123.5c8.2-7.7 8.6-20.6 0.8-28.8zm-282.6,253.9h-50.6c-53.9,0-98.9-38.8-108.5-89.9h267.5c-9.6,51.1-54.5,89.9-108.4,89.9z" />
        <path d="M97.6,254.9c11.3,0,20.4-9.1,20.4-20.4V114c0-11.3-9.1-20.4-20.4-20.4c-11.3,0-20.4,9.1-20.4,20.4v120.5    C77.2,245.8,86.3,254.9,97.6,254.9z">
          <animateTransform
            attributeName="transform"
            type="translate"
            values="0 0; 0 20; 0 0"
            dur="1s"
            keyTimes="0;0.5;1"
            repeatCount="indefinite"
          />
        </path>
        <path d="m271.1,254.9c11.3,0 20.4-9.1 20.4-20.4v-120.5c0-11.3-9.1-20.4-20.4-20.4-11.3,0-20.4,9.1-20.4,20.4v120.5c-2.84217e-14,11.3 9.1,20.4 20.4,20.4z">
          <animateTransform
            attributeName="transform"
            type="translate"
            values="0 0; 0 20; 0 0"
            dur="1s"
            keyTimes="0;0.5;1"
            begin="0.2s"
            repeatCount="indefinite"
          />
        </path>
        <path d="m184.3,173.9c11.3,0 20.4-9.1 20.4-20.4v-122c0-11.3-9.1-20.4-20.4-20.4s-20.4,9.1-20.4,20.4v122c0,11.2 9.2,20.4 20.4,20.4z">
          <animateTransform
            attributeName="transform"
            type="translate"
            values="0 0; 0 20; 0 0"
            dur="1s"
            keyTimes="0;0.5;1"
            begin="0.4s"
            repeatCount="indefinite"
          />
        </path>
      </g>
    </g>
  </svg>
);

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              padding: "16px",
              borderBottom: "1px solid grey",
              boxShadow: "rgba(0, 0, 0, 0.05) 0px 1px 2px 0px",
            }}
          >
            {panAnimatedSvg} <ThemeSwitcher />
          </div>

          {children}
        </Providers>
      </body>
    </html>
  );
}
